import localFont from "next/font/local";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend+Mega:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <header>
        <div>
          <h1>Neo Brutalism</h1>
        </div>
      </header>
      <div className="introduction">
        <h2>
          Neo-Brutalism is a modern design trend inspired by the raw, bold, and
          functional aesthetic of mid-20th century Brutalism. It emphasizes
          simplicity, geometric shapes, flat colors, and minimal decoration.
          This site will guide you through creating basic components using the
          Neo-Brutalism style.
        </h2>
      </div>
      <div className="buttonIntroduction">
        <h2 className="buttonSectionTitle">Button</h2>
      </div>
      <div className="contentContainer">
        <div className="content">
          <div className="buttonBox">
            <button>button</button>
          </div>
          <div>
            <div className="scrollBox">
              <pre>
                {`
  /* Button html */

  <button>button</button>

  /* Button CSS */
  
  button{
    width:200px;
    height: 50px;
    font-family: "Lexend Mega", sans-serif;
    font-weight: 700;
    background-color: #ff00f5;
    color: white;
    border-radius: 10px;
    border: 3px solid black;
    box-shadow: 2px 3px black;
  }
  button:hover{
    box-shadow: 4px 6px black;
    cursor: pointer;
  }
  button:active{
    background-color: #ff00f7b2;
  }
`}
              </pre>
            </div>
          </div>
        </div>
      </div>
      <div className="cardIntroduction">
        <h2 className="cardSectionTitle">Card</h2>
      </div>

      <div className="contentContainer2">
        <div className="content2">
          <div>
            <div className="scrollBoxCard">
              <pre>
                {`
  /* Card html */

  <div className="cardBox">
    <div className="imageBox">
      <Image src="./globe.svg" width={100} height={100} />
    </div>
    <h1>Title</h1>
    <p>Here is where you will add the card's description</p>
  </div>
  
  /* Card CSS */

  .cardBox{
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    border-radius: 10px;
    border: 3px solid black;
    box-shadow: 2px 3px black;
    width: 300px;
    height: 300px;
    background-color: #3300ff;69d2e7
    text-align: center;
    color:white;

  }
  .imageBox{
    width: 250px;
    height: 200px;
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 10px;
    border: 3px solid black;
    box-shadow: 2px 3px black;
    margin: 10px;
    background-color: #69d2e7;3300ff
  }
`}
              </pre>
            </div>
          </div>
          <div style={{backgroundColor:"#3300ff", }} className="inputBox">
            <div className="cardBox">
              <div className="imageBox">
                <Image src="./globe.svg" width={30} height={30} />
              </div>
              <h1>Title</h1>
              <p>Here is where you will add the card's description</p>
            </div>
          </div>
        </div>
      </div>
      <div className="textIntroduction">
        <h2 className="textSectionTitle">Text Input</h2>
      </div>
      <div className="contentContainer3">
        <div className="content3">
          <div className="inputBox">
            <input type="text" placeholder="Enter text here" />
          </div>
          <div>
            <div className="scrollBox">
              <pre>
                {`
  /* Input html */

    <input type="text" placeholder="Enter text here" />
  
  /* Input CSS */

  input{
    width: 200px;
    height: 30px;
    border-radius: 10px;
    border: 3px solid black;
    box-shadow: 2px 3px black;
    margin: 10px;
    font-family: "Lexend Mega", sans-serif;
    outline: none;

  }
  input:focus{
    box-shadow: 4px 6px black;
  }
`}
              </pre>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
